services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
    volumes:
      - /home/talcantara/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /home/talcantara/mosquitto/data:/mosquitto/data
      - /home/talcantara/mosquitto/log:/mosquitto/log
  uart-lora-service:
    build: ./uart_service
    container_name: sonda-lora-service
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
    devices:
     # remember to run sudo chmod 666 /dev/ttyAMA0 on the host system
      - "/dev/ttyAMA0:/dev/ttyAMA0"
  sonda-web:
    build: ./webapp
    container_name: sonda-web
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
    ports:
      - "5000:5000"
